export const columns: any[] = ["Ranking", "wallet address", "tikkets"];
export const rows: any[] = [
  ['1 <img src="up.png" />', "danieldalen.eth", 213],
  ['2 <img src="down.png" />', "iwillwinthisforsure.eth", 248],
  ['3 <img src="up.png" />', "0x8E45cbB9bAf6fREG4d0D0d3A81DF478b22091e1f", 150],
  ['4 <img src="up.png" />', "punk3251.eth", 134],
];
export const faqItems: any[] = [
  {
    title: "How often do we do giveaways",
    content:
      "We aim to do one at least every week - we’re a new company that recently launched, so we’ll release more details on the giveaways as soon as possible collecting feedback from the community.",
  },
  {
    title: "How does Tikket work?",
    content:
      "We aim to do one at least every week - we’re a new company that recently launched, so we’ll release more details on the giveaways as soon as possible collecting feedback from the community.",
  },
  {
    title: "How soon do you receive the NFT ",
    content:
      "We aim to do one at least every week - we’re a new company that recently launched, so we’ll release more details on the giveaways as soon as possible collecting feedback from the community.",
  },
  {
    title: "If you don’t win, do the tikkets still have a value?",
    content:
      "We aim to do one at least every week - we’re a new company that recently launched, so we’ll release more details on the giveaways as soon as possible collecting feedback from the community.",
  },
];
export const behindList: any[] = [
  {
    img: "img2.png",
    name: "DANIEL",
    socials: { twitter: "/", instagram: "/" },
  },
  { img: "img3.png", name: "ADAM", socials: { twitter: "/", instagram: "/" } },
  { img: "img4.png", name: "ANDRE", socials: { twitter: "/", instagram: "/" } },
  {
    img: "img5.png",
    name: "KOZLOV",
    socials: { twitter: "/", instagram: "/" },
  },
];
export const ticket_rows: any[] = [
  ['1 <img src="up.png" />', "danieldalen.eth", 213],
  ['2 <img src="down.png" />', "iwillwinthisforsure.eth", 248],
  ['3 <img src="up.png" />', "0x8E45cbB9bAf6fREG4d0D0d3A81DF478b22091e1f", 150],
  ['4 <img src="up.png" />', "sdfsdfsdfs.eth", 134],
  ['5 <img src="up.png" />', "punk3251.eth", 134],
  ['6 <img src="up.png" />', "punk3251.eth", 134],
  ['7 <img src="up.png" />', "punkdf3251.eth", 222],
  ['8 <img src="up.png" />', "punk3251.eth", 134],
  ['9 <img src="up.png" />', "sdfsdfsdfs.eth", 134],
  ['10 <img src="up.png" />', "punk3251.eth", 334],
  ['11 <img src="up.png" />', "punk3251.eth", 134],
  ['12 <img src="up.png" />', "34etrterte.eth", 134],
  ['13 <img src="up.png" />', "rrrterte.eth", 134],
  ['14 <img src="up.png" />', "punk3251.eth", 134],
  ['15 <img src="up.png" />', "punkfghf3251.eth", 55],
  ['16 <img src="up.png" />', "punk3251.eth", 134],
  ['17 <img src="up.png" />', "ytryrtyrytr.eth", 134],
  ['18 <img src="up.png" />', "punk3251.eth", 134],
  ['19 <img src="up.png" />', "fghfgh.eth", 134],
  ['20 <img src="up.png" />', "trtyrtyrytr.eth", 134],
  ['21 <img src="up.png" />', "punk3251.eth", 134],
  ['22 <img src="up.png" />', "punk3251.eth", 134],
  ['23 <img src="up.png" />', "dgjhghjghjg.eth", 134],
  ['24 <img src="up.png" />', "punk3251.eth", 134],
  ['25 <img src="up.png" />', "punk3251.eth", 134],
  ['26 <img src="up.png" />', "4564564tr.eth", 134],
  ['27 <img src="up.png" />', "punk3251.eth", 134],
  ['28 <img src="up.png" />', "punk3251.eth", 134],
  ['29 <img src="up.png" />', "rtyrtyrtyr.eth", 134],
  ['30 <img src="up.png" />', "punk3251.eth", 134],
  ['31 <img src="up.png" />', "ewtertdfgdfgd.eth", 134],
  ['32 <img src="up.png" />', "punk3251.eth", 134],
  ['33 <img src="up.png" />', "punk3251.eth", 134],
  ['34 <img src="up.png" />', "dfgdfgd.eth", 134],
  ['35 <img src="up.png" />', "punk3251.eth", 134],
  ['36 <img src="up.png" />', "tyrtyrty.eth", 134],
  ['37 <img src="up.png" />', "cvbcvbcvbcbvc.eth", 134],
  ['38 <img src="up.png" />', "punk3251.eth", 134],
  ['39 <img src="up.png" />', "punk3251.eth", 134],
  ['40 <img src="up.png" />', "ertertert.eth", 134],
  ['41 <img src="up.png" />', "punk3251.eth", 134],
  ['42 <img src="up.png" />', "dfgdfgdfgdfgdfgdfgdfgdfgd.eth", 134],
  ['43 <img src="up.png" />', "punk3251.eth", 134],
  ['44 <img src="up.png" />', "punk3251.eth", 134],
  ['45 <img src="up.png" />', "ertjjyyj.eth", 134],
  ['46 <img src="up.png" />', "punk3251.eth", 134],
  ['47 <img src="up.png" />', "cxbvv.eth", 134],
  ['48 <img src="up.png" />', "punk3251.eth", 134],
  ['49 <img src="up.png" />', "punk3251.eth", 134],
  ['50 <img src="up.png" />', "punk3251.eth", 134],
  ['51 <img src="up.png" />', "erterterte.eth", 134],
  ['52 <img src="up.png" />', "punk3251.eth", 134],
  ['53 <img src="up.png" />', "punk3251.eth", 134],
  ['54 <img src="up.png" />', "rtyrtyrtyrty.eth", 134],
  ['55 <img src="up.png" />', "punk3251.eth", 134],
  ['56 <img src="up.png" />', "punk3251.eth", 134],
  ['57 <img src="up.png" />', "punk3251.eth", 134],
  ['58 <img src="up.png" />', "ghjghjghj.eth", 134],
  ['59 <img src="up.png" />', "punk3251.eth", 134],
  ['60 <img src="up.png" />', "punk3251.eth", 134],
];
